### ISSUE TITLE
Doesn't work with Tetris Battle Gaiden

### ISSUE THREAD

**Issue by gnaghi** [breakin/snestistics#11]
I have the following message with Tetris Battle Gaiden (Sha256 7a96458b60507b60b581b7a1ba32f2855cff18d6f13bfeb45ad161dd469c5c61 Lorom game), after stopping the emulation on the title screen :

> Loading ROM 'Tetris Battle Gaiden.sfc'
> Load ROM data...
>   Header Size:    0x000000
>   Calculated Size 0x100000 (1024 kb)
> Create trace using emulation...
> 100 nmi emulated
> 200 nmi emulated
> 300 nmi emulated
> 400 nmi emulated
> 500 nmi emulated
> 600 nmi emulated
> Found diff AFTER at op 15178957
> P  0025 0025 0025
>     <Carry IRQ MemoryFlag >
>     <Carry IRQ MemoryFlag >
>     <Carry IRQ MemoryFlag >
>     <Carry IRQ MemoryFlag >
> A    7F01 7F01 7F01
> X    0108 0108 0108
> Y    8000 8000 8000
> S    1FEB 1FEB 1FEB
> DB   83 83 83
> DP   0000 0000 0000
> PC   83F2B0 83F2B3 83F2B3
> WRAM 010000 010000 018000
> This means that the snestistics emulator can't emulate this game yet.
> This diff is done against .trace_helper which codifies some state that is tested against

**Comment by breakin** [comment]
So first welcome to snestistics! I think you are the first user so that is fun! I can reproduce your issue and I will fix it!

**Comment by breakin** [comment]
This error should be fixed in https://github.com/breakin/snestistics/releases/tag/v0.002
If the error persist or if new errors present themselves, don't hesitate to open new issues or re-open this issue!

**Comment by gnaghi** [comment]
That was fast 👍  :)
